project:
  type: website
  output-dir: docs
website:
  title: "trevor-edgull-portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: "About Me"
      - href: portfolio-final/TEdgull_Final_Project.qmd
        text: "The Simpson Analysis"




format:
  html:
    theme:
      - cyborg
      - brand
    css: styles.css
    toc: true

editor: visual

